version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysql_data:
